# Generated by Django 4.1.1 on 2022-09-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastDegreesToRadiansResults',
            new_name='PastDegreesToRadiansResult',
        ),
    ]
