# Generated by Django 4.1.1 on 2022-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_pastdegreestoradiansresult_degress_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='degress_input',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='degress_result',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='minutes_input',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='radians_output',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='seconds_input',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
