# Generated by Django 4.1.1 on 2022-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_pastdegreestoradiansresult_radians_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='degress_input',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
