# Generated by Django 4.1.1 on 2022-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_pastdegreestoradiansresult_degress_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='degress_input',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='minutes_input',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pastdegreestoradiansresult',
            name='seconds_input',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
