apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-restapi-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress_class }}
spec:
  rules:
  - host: {{ .Values.global.restapi_url }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-restapi-service
            port: 
              number: 80
{{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.restapi_url }}
      secretName: {{ .Values.tls.restapi_cert }}
{{- end -}}