---
apiVersion: v1
kind: Service
metadata:
  name: galera-cluster-mariadb-galera-dev-lb
  namespace: cicd-practice-1
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: galera-cluster
    app.kubernetes.io/name: mariadb-galera
  type: LoadBalancer
