---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-cluster-dev-lb
  namespace: cicd-practice-1
spec:
  ports:
    - name: tcp-hzport
      protocol: TCP
      port: 5701
      targetPort: hazelcast
  selector:
    app.kubernetes.io/instance: hazelcast-cluster
    app.kubernetes.io/name: hazelcast
    role: hazelcast
  type: LoadBalancer