{{- if .Values.restapi.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-restapi-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-restapi-deployment
  minReplicas: {{ .Values.restapi.min_replicas }}
  maxReplicas: {{ .Values.restapi.hpa.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.restapi.hpa.avg_cpu_util }}
{{- end -}}