apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-restapi-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  django_secret_key: {{ .Values.restapi.secret_key | quote }}
  django_db_password: {{ .Values.restapi.db_password | quote }}