apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-restapi-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: restapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: restapi