global:
  pull_secret:   
  log_level: INFO
  ingress_class: nginx
  frontend_url: 
  restapi_url: 
  static_url: 

tls:
  enabled: true
  frontend_cert: 
  restapi_cert: 
  static_cert: 
    
frontend:
  min_replicas: 2
  image: 
  pull_policy: Always
  requests_cpu: 100m
  requests_mem: 32Mi
  limits_cpu: 200m
  limits_mem: 128Mi
  hpa:
    enabled: true
    avg_cpu_util: 50
    max_replicas: 5

restapi:
  min_replicas: 2
  image: 
  pull_policy: Always
  secret_key: 
  db_password: 
  db_username: django
  db_engine: mysql
  db_name: django
  db_host: 
  cache_engine: django.core.cache.backends.memcached.PyMemcacheCache
  cache_host: 
  requests_cpu: 250m
  requests_mem: 64Mi
  limits_cpu: 500m
  limits_mem: 256Mi
  hpa:
    enabled: true
    avg_cpu_util: 50
    max_replicas: 5

static:
  min_replicas: 2
  image: 
  pull_policy: Always
  requests_cpu: 100m
  requests_mem: 32Mi
  limits_cpu: 200m
  limits_mem: 128Mi
  hpa:
    enabled: true
    avg_cpu_util: 50
    max_replicas: 5